meteor add jquery
meteor add bootstrap
meteor add accounts-base
meteor add accounts-password
meteor add accounts-ui
meteor add mquandalle:jade
meteor add iron:router
meteor add alanning:roles
meteor add dburles:mongo-collection-instances